-- seed-productos.sql - GENERADO por tools/seed-supabase.js desde
-- D:\GunShop\js\catalog.js (o el mismo repo en ..\GunShop desde este
-- worktree). No editar a mano.
--
-- Reconstruir:  node tools/seed-supabase.js
--
-- Trae los 76 productos y las 102 referencias del catalogo real, encima
-- de lo que ya deja seed.sql (family/licence_regime/location/fx_rate).
-- Idempotente: cada insert entra por su clave natural. product usa
-- ON CONFLICT ... DO UPDATE (corrige precio/regimen/ficha si ya estaba
-- de la semilla de 18 de muestra; catalog.js es la unica fuente de
-- verdad); el resto, DO NOTHING. No toca cart/sales_order/customer ni
-- ninguna tabla de pedidos o clientes -- no las nombra, y order_item
-- guarda su propia copia congelada de lo que se vendio.

insert into public.brand (slug, name, country) values
  ('aimpoint', 'Aimpoint', null),
  ('anschutz', 'Anschütz', null),
  ('arregui', 'Arregui', 'ES'),
  ('arrieta', 'Arrieta', 'ES'),
  ('aya', 'AyA', null),
  ('benelli', 'Benelli', 'IT'),
  ('beretta', 'Beretta', null),
  ('bergara', 'Bergara', null),
  ('blaser', 'Blaser', 'DE'),
  ('browning', 'Browning', 'BE'),
  ('cci', 'CCI', 'US'),
  ('cz', 'CZ', 'CZ'),
  ('eley', 'Eley', 'GB'),
  ('fabarm', 'Fabarm', 'IT'),
  ('federal', 'Federal', null),
  ('feinwerkbau', 'Feinwerkbau', 'DE'),
  ('fiocchi', 'Fiocchi', 'IT'),
  ('glock', 'Glock', null),
  ('grulla-armas', 'Grulla Armas', 'ES'),
  ('holosun', 'Holosun', 'US'),
  ('hoppe-s', 'Hoppe''s', 'US'),
  ('hornady', 'Hornady', null),
  ('kahles', 'Kahles', 'AT'),
  ('lapua', 'Lapua', 'FI'),
  ('leica', 'Leica', 'DE'),
  ('leupold', 'Leupold', null),
  ('mauser', 'Mauser', 'DE'),
  ('merkel', 'Merkel', 'DE'),
  ('morini', 'Morini', 'CH'),
  ('negrini', 'Negrini', null),
  ('norma', 'Norma', 'SE'),
  ('otis', 'Otis', null),
  ('pardini', 'Pardini', null),
  ('peli', 'Peli', 'US'),
  ('plano', 'Plano', 'US'),
  ('rio', 'RIO', 'ES'),
  ('rws', 'RWS', 'DE'),
  ('rottner', 'Rottner', 'DE'),
  ('saga', 'SAGA', 'ES'),
  ('sig-sauer', 'SIG Sauer', 'DE'),
  ('sako', 'Sako', 'FI'),
  ('sauer', 'Sauer', 'DE'),
  ('sellier', 'Sellier & Bellot', null),
  ('steyr', 'Steyr', 'AT'),
  ('swarovski', 'Swarovski', null),
  ('tikka', 'Tikka', null),
  ('vortex', 'Vortex', 'US'),
  ('walther', 'Walther', null),
  ('winchester', 'Winchester', 'US'),
  ('zeiss', 'Zeiss', 'DE'),
  ('zoli', 'Zoli', 'IT')
on conflict (slug) do nothing;
insert into public.calibre (name, bore_mm, smoothbore, rimfire, airgun, annual_quota) values
  ('.22 LR', 5.6, false, true, false, 2500),
  ('.223 Rem', 5.7, false, false, false, 1000),
  ('.30-06 Sprg', 7.82, false, false, false, 1000),
  ('.300 Win Mag', 7.82, false, false, false, 1000),
  ('.308 Win', 7.82, false, false, false, 1000),
  ('4,5 mm', 4.5, false, false, true, 0),
  ('6,5 Creedmoor', 6.71, false, false, false, 1000),
  ('8x57 IS', 8.2, false, false, false, 1000),
  ('9 mm Pb', 9.02, false, false, false, 1000),
  ('9,3x62', 9.3, false, false, false, 1000),
  ('cal. 12/70', 18.5, true, false, false, 2500),
  ('cal. 12/76', 18.5, true, false, false, 2500),
  ('cal. 12/89', 18.5, true, false, false, 2500),
  ('cal. 20/70', 15.6, true, false, false, 2500),
  ('cal. 20/76', 15.6, true, false, false, 2500)
on conflict (name) do nothing;
insert into public.product (brand_id, family_id, ref, kind, spec, licence_regime_id,
                            usd_cents, serialized, cartridges_per_box)
select b.id, f.id, v.ref, v.kind, v.spec,
       (select r.id from public.licence_regime r where r.code = v.licence),
       v.usd_cents, v.serialized, v.cartuchos
  from (values
  ('bergara', 'rifles', 'B-14 Ridge', 'Rifle de cerrojo', array['cañón 560 mm', '3,2 kg'], null::text, 191000, true, 0),
  ('bergara', 'rifles', 'B-14 HMR', 'Rifle de precisión', array['cañón 610 mm', '4,3 kg'], null::text, 260000, true, 0),
  ('tikka', 'rifles', 'T3x Lite', 'Rifle de cerrojo', array['cañón 570 mm', '2,9 kg'], null::text, 210000, true, 0),
  ('tikka', 'rifles', 'T3x Varmint', 'Rifle de precisión', array['cañón 600 mm', '4,0 kg'], null::text, 245000, true, 0),
  ('sako', 'rifles', '85 Bavarian', 'Rifle de cerrojo', array['cañón 570 mm', '3,4 kg', 'culata de nogal'], null::text, 400000, true, 0),
  ('sako', 'rifles', 'S20 Hunter', 'Rifle modular', array['cañón 610 mm', '3,4 kg'], null::text, 330000, true, 0),
  ('blaser', 'rifles', 'R8 Professional', 'Rifle rectilíneo', array['cañón 580 mm', '3,4 kg', 'cañón intercambiable'], null::text, 645000, true, 0),
  ('sauer', 'rifles', '100 Classic XT', 'Rifle de cerrojo', array['cañón 560 mm', '3,2 kg'], null::text, 165000, true, 0),
  ('mauser', 'rifles', 'M12 Pure', 'Rifle de cerrojo', array['cañón 560 mm', '3,3 kg'], null::text, 315000, true, 0),
  ('browning', 'rifles', 'X-Bolt Hunter', 'Rifle de cerrojo', array['cañón 560 mm', '3,2 kg'], null::text, 220000, true, 0),
  ('merkel', 'rifles', 'Helix Alpinist', 'Rifle rectilíneo', array['cañón 560 mm', '3,1 kg'], null::text, 560000, true, 0),
  ('browning', 'rifles', 'BAR MK3', 'Rifle semiautomático', array['cañón 530 mm', '3,3 kg'], null::text, 280000, true, 0),
  ('benelli', 'rifles', 'Argo E Comfort', 'Rifle semiautomático', array['cañón 510 mm', '3,3 kg'], null::text, 295000, true, 0),
  ('cz', 'rifles', '457 Varmint', 'Rifle del 22', array['cañón 525 mm', '3,2 kg'], 'uso-civil', 121000, true, 0),
  ('anschutz', 'rifles', '1761 HB', 'Rifle del 22', array['cañón 560 mm', '3,4 kg', 'gatillo ajustable'], 'uso-civil', 280000, true, 0),
  ('aya', 'escopetas', 'No. 4/53', 'Paralela · Eibar', array['cañón 710 mm', '3,1 kg', 'extractores'], null::text, 585000, true, 0),
  ('aya', 'escopetas', 'No. 1 De Luxe', 'Paralela · Eibar', array['cañón 710 mm', '3,0 kg', 'grabado a mano'], null::text, 830000, true, 0),
  ('grulla-armas', 'escopetas', '216 RB', 'Paralela · Eibar', array['cañón 710 mm', '3,0 kg', 'culata a medida'], null::text, 885000, true, 0),
  ('arrieta', 'escopetas', '557', 'Paralela · Elgoibar', array['cañón 710 mm', '3,1 kg', 'llaves Holland'], null::text, 695000, true, 0),
  ('beretta', 'escopetas', '686 Silver Pigeon I', 'Superpuesta de caza', array['cañón 710 mm', '3,3 kg', '5 chokes'], null::text, 370000, true, 0),
  ('beretta', 'escopetas', '690 Field III', 'Superpuesta de caza', array['cañón 710 mm', '3,4 kg', 'Steelium'], null::text, 525000, true, 0),
  ('browning', 'escopetas', 'B525 Game One', 'Superpuesta de caza', array['cañón 710 mm', '3,3 kg'], null::text, 340000, true, 0),
  ('browning', 'escopetas', 'B725 Sporter', 'Superpuesta de tiro', array['cañón 760 mm', '3,7 kg', 'banda ventilada'], null::text, 475000, true, 0),
  ('fabarm', 'escopetas', 'Elos N2 Allsport', 'Superpuesta de tiro', array['cañón 760 mm', '3,6 kg'], null::text, 320000, true, 0),
  ('zoli', 'escopetas', 'Z-Sport', 'Superpuesta de tiro', array['cañón 810 mm', '3,9 kg', 'culata regulable'], null::text, 1155000, true, 0),
  ('benelli', 'escopetas', 'Raffaello Crio', 'Semiautomática', array['cañón 710 mm', '3,0 kg', 'sistema inercial'], 'uso-civil-condicional', 300000, true, 0),
  ('beretta', 'escopetas', 'A400 Xtreme Plus', 'Semiautomática', array['cañón 760 mm', '3,4 kg', 'Kick-Off'], 'uso-civil-condicional', 340000, true, 0),
  ('winchester', 'escopetas', 'SX4 Field', 'Semiautomática', array['cañón 710 mm', '3,2 kg'], 'uso-civil-condicional', 151000, true, 0),
  ('pardini', 'pistolas', 'SP', 'Pistola de precisión', array['cañón 152 mm', 'gatillo 1.000 g'], 'uso-civil', 320000, true, 0),
  ('pardini', 'pistolas', 'K12 Absorber', 'Pistola de aire', array['gatillo 500 g', '940 g'], 'aire-comprimido', 260000, false, 0),
  ('walther', 'pistolas', 'GSP Expert', 'Pistola de precisión', array['cañón 152 mm', 'gatillo 1.000 g'], 'uso-civil', 400000, true, 0),
  ('walther', 'pistolas', 'LP500 Expert', 'Pistola de aire', array['gatillo 500 g', '960 g'], 'aire-comprimido', 340000, false, 0),
  ('morini', 'pistolas', 'CM 162 EI', 'Pistola de aire', array['gatillo 500 g', '940 g'], 'aire-comprimido', 290000, false, 0),
  ('feinwerkbau', 'pistolas', 'AW93', 'Pistola de precisión', array['cañón 153 mm', 'gatillo 1.000 g'], 'uso-civil', 360000, true, 0),
  ('steyr', 'pistolas', 'EVO 10 E', 'Pistola de aire', array['gatillo 500 g', '960 g'], 'aire-comprimido', 270000, false, 0),
  ('beretta', 'pistolas', '92X Performance', 'Arma corta de tiro', array['cañón 125 mm', '15+1'], null::text, 260000, true, 0),
  ('cz', 'pistolas', 'Shadow 2', 'Arma corta de tiro', array['cañón 120 mm', '17+1'], null::text, 300000, true, 0),
  ('glock', 'pistolas', '17 Gen5', 'Arma corta de tiro', array['cañón 114 mm', '17+1'], null::text, 139000, true, 0),
  ('sig-sauer', 'pistolas', 'P226 LDC II', 'Arma corta de tiro', array['cañón 112 mm', '15+1'], null::text, 320000, true, 0),
  ('swarovski', 'optica', 'Z8i 2-16x50 P', 'Visor de caza', array['retícula 4A-I', 'tubo 30 mm', '630 g'], null::text, 790000, false, 0),
  ('swarovski', 'optica', 'Z6i 2,5-15x56', 'Visor de caza', array['retícula 4A-I', 'tubo 30 mm', '660 g'], null::text, 620000, false, 0),
  ('zeiss', 'optica', 'Conquest V4 3-12x56', 'Visor de caza', array['retícula 60', 'tubo 30 mm', '640 g'], null::text, 310000, false, 0),
  ('zeiss', 'optica', 'Victory V8 2,8-20x56', 'Visor de larga distancia', array['retícula 60', 'tubo 36 mm', '800 g'], null::text, 815000, false, 0),
  ('leupold', 'optica', 'VX-3HD 3,5-10x50', 'Visor de caza', array['retícula Duplex', 'tubo 30 mm', '470 g'], null::text, 154000, false, 0),
  ('vortex', 'optica', 'Viper PST Gen II 5-25x50', 'Visor de tiro', array['retícula EBR-7C', 'tubo 30 mm', 'torretas de tiro'], null::text, 285000, false, 0),
  ('kahles', 'optica', 'K18i 1-8x24', 'Visor de batida', array['retícula 3GR', 'tubo 30 mm', '510 g'], null::text, 550000, false, 0),
  ('aimpoint', 'optica', 'Micro H-2 2 MOA', 'Punto rojo', array['montura Picatinny', '105 g'], null::text, 197000, false, 0),
  ('aimpoint', 'optica', 'Acro P-2 3,5 MOA', 'Punto rojo', array['cierre estanco', '60 g'], null::text, 154000, false, 0),
  ('holosun', 'optica', 'HS507C X2', 'Punto rojo', array['retícula múltiple', '44 g'], null::text, 82000, false, 0),
  ('swarovski', 'optica', 'EL 10x42 WB', 'Prismáticos', array['campo 133 m/1.000', '840 g'], null::text, 600000, false, 0),
  ('zeiss', 'optica', 'Victory SF 10x42', 'Prismáticos', array['campo 120 m/1.000', '780 g'], null::text, 645000, false, 0),
  ('leica', 'optica', 'Geovid R 10x42', 'Prismáticos telémetro', array['alcance 1.100 m', '950 g'], null::text, 525000, false, 0),
  ('vortex', 'optica', 'Diamondback HD 10x42', 'Prismáticos', array['campo 104 m/1.000', '780 g'], null::text, 70000, false, 0),
  ('federal', 'municion', 'Power-Shok .308 Win 150 gr', 'Cartuchería metálica', array['punta blanda', 'caja de 20'], null::text, 7000, false, 20),
  ('hornady', 'municion', 'Precision Hunter 6,5 Creedmoor 143 gr', 'Cartuchería metálica', array['punta ELD-X', 'caja de 20'], null::text, 11500, false, 20),
  ('hornady', 'municion', 'Superformance .30-06 Sprg 165 gr', 'Cartuchería metálica', array['punta SST', 'caja de 20'], null::text, 11000, false, 20),
  ('rws', 'municion', 'Evolution Green .308 Win 139 gr', 'Cartuchería sin plomo', array['sin plomo', 'caja de 20'], null::text, 15000, false, 20),
  ('norma', 'municion', 'Oryx .30-06 Sprg 180 gr', 'Cartuchería metálica', array['núcleo soldado', 'caja de 20'], null::text, 12500, false, 20),
  ('sellier', 'municion', '.308 Win 147 gr', 'Cartuchería de práctica', array['FMJ', 'caja de 20'], null::text, 5000, false, 20),
  ('lapua', 'municion', 'Scenar-L 6,5 Creedmoor 136 gr', 'Cartuchería match', array['punta hueca', 'caja de 50'], null::text, 18500, false, 50),
  ('cci', 'municion', 'Standard Velocity .22 LR 40 gr', 'Cartuchería del 22', array['plomo', 'caja de 50'], null::text, 2800, false, 50),
  ('eley', 'municion', 'Tenex .22 LR 40 gr', 'Cartuchería match', array['selección de lote', 'caja de 50'], null::text, 5800, false, 50),
  ('rio', 'municion', 'Game Load BlueSteel cal. 12/70', 'Cartuchería de caza', array['acero 32 g', 'caja de 25'], null::text, 2200, false, 25),
  ('saga', 'municion', 'Heavy 34 cal. 12/70', 'Cartuchería de caza', array['plomo 34 g del 6', 'caja de 25'], null::text, 2400, false, 25),
  ('fiocchi', 'municion', 'Golden Pheasant cal. 12/70', 'Cartuchería de caza', array['plomo 36 g del 5', 'caja de 25'], null::text, 4100, false, 25),
  ('winchester', 'municion', 'Super X cal. 12/76', 'Cartuchería de caza', array['plomo 36 g del 4', 'caja de 25'], null::text, 3100, false, 25),
  ('peli', 'accesorios', '1750 Protector', 'Maleta rígida', array['128 cm', 'espuma precortada', 'purga de presión'], null::text, 85000, false, 0),
  ('peli', 'accesorios', '1720 Protector', 'Maleta rígida', array['107 cm', 'cierre estanco IP67'], null::text, 72000, false, 0),
  ('negrini', 'accesorios', '1657', 'Maleta para superpuesta', array['82 cm', 'forro de terciopelo'], null::text, 53000, false, 0),
  ('plano', 'accesorios', 'All Weather 42"', 'Maleta rígida', array['107 cm', 'cierres de leva'], null::text, 33000, false, 0),
  ('beretta', 'accesorios', 'Hunter Tech Rifle Case', 'Funda blanda', array['130 cm', 'acolchado', 'bandolera'], null::text, 16500, false, 0),
  ('beretta', 'accesorios', 'Uniform Pro EVO Field Bag', 'Bolsa de campo', array['45 l', 'loneta encerada'], null::text, 45000, false, 0),
  ('arregui', 'accesorios', 'Braco 5', 'Armero homologado', array['5 plazas', 'grado I', 'anclaje a muro'], null::text, 113000, false, 0),
  ('rottner', 'accesorios', 'Gun 5 Cargo', 'Armero homologado', array['5 plazas', 'cerradura electrónica'], null::text, 91000, false, 0),
  ('hoppe-s', 'accesorios', 'No. 9 Deluxe Kit', 'Estuche de limpieza', array['32 piezas', 'estuche de nogal'], null::text, 14000, false, 0),
  ('otis', 'accesorios', 'Elite Cleaning System', 'Estuche de limpieza', array['40 piezas', 'multicalibre'], null::text, 43000, false, 0)
  ) as v(brand, family, ref, kind, spec, licence, usd_cents, serialized, cartuchos)
  join public.brand  b on b.slug = v.brand
  join public.family f on f.slug = v.family
on conflict (brand_id, ref) do update set
  kind = excluded.kind,
  spec = excluded.spec,
  licence_regime_id = excluded.licence_regime_id,
  usd_cents = excluded.usd_cents,
  serialized = excluded.serialized,
  cartridges_per_box = excluded.cartridges_per_box;

insert into public.product_variant (product_id, calibre_id, sku, position)
select p.id, c.id, v.sku, v.position
  from (values
  ('bergara', 'B-14 Ridge', '.308 Win', 'BERGARA-B14RIDGE-308WIN', 1),
  ('bergara', 'B-14 Ridge', '.30-06 Sprg', 'BERGARA-B14RIDGE-3006SPRG', 2),
  ('bergara', 'B-14 Ridge', '6,5 Creedmoor', 'BERGARA-B14RIDGE-65CREEDMOOR', 3),
  ('bergara', 'B-14 HMR', '6,5 Creedmoor', 'BERGARA-B14HMR-65CREEDMOOR', 1),
  ('bergara', 'B-14 HMR', '.308 Win', 'BERGARA-B14HMR-308WIN', 2),
  ('tikka', 'T3x Lite', '.308 Win', 'TIKKA-T3XLITE-308WIN', 1),
  ('tikka', 'T3x Lite', '.30-06 Sprg', 'TIKKA-T3XLITE-3006SPRG', 2),
  ('tikka', 'T3x Lite', '.300 Win Mag', 'TIKKA-T3XLITE-300WINMAG', 3),
  ('tikka', 'T3x Varmint', '.223 Rem', 'TIKKA-T3XVARMINT-223REM', 1),
  ('tikka', 'T3x Varmint', '.308 Win', 'TIKKA-T3XVARMINT-308WIN', 2),
  ('sako', '85 Bavarian', '.30-06 Sprg', 'SAKO-85BAVARIAN-3006SPRG', 1),
  ('sako', '85 Bavarian', '9,3x62', 'SAKO-85BAVARIAN-93X62', 2),
  ('sako', 'S20 Hunter', '.308 Win', 'SAKO-S20HUNTER-308WIN', 1),
  ('sako', 'S20 Hunter', '6,5 Creedmoor', 'SAKO-S20HUNTER-65CREEDMOOR', 2),
  ('blaser', 'R8 Professional', '.30-06 Sprg', 'BLASER-R8PROFESSIONAL-3006SPRG', 1),
  ('blaser', 'R8 Professional', '8x57 IS', 'BLASER-R8PROFESSIONAL-8X57IS', 2),
  ('blaser', 'R8 Professional', '9,3x62', 'BLASER-R8PROFESSIONAL-93X62', 3),
  ('blaser', 'R8 Professional', '.300 Win Mag', 'BLASER-R8PROFESSIONAL-300WINMAG', 4),
  ('sauer', '100 Classic XT', '.308 Win', 'SAUER-100CLASSICXT-308WIN', 1),
  ('sauer', '100 Classic XT', '.30-06 Sprg', 'SAUER-100CLASSICXT-3006SPRG', 2),
  ('mauser', 'M12 Pure', '.308 Win', 'MAUSER-M12PURE-308WIN', 1),
  ('mauser', 'M12 Pure', '.30-06 Sprg', 'MAUSER-M12PURE-3006SPRG', 2),
  ('mauser', 'M12 Pure', '9,3x62', 'MAUSER-M12PURE-93X62', 3),
  ('browning', 'X-Bolt Hunter', '.308 Win', 'BROWNING-XBOLTHUNTER-308WIN', 1),
  ('browning', 'X-Bolt Hunter', '.30-06 Sprg', 'BROWNING-XBOLTHUNTER-3006SPRG', 2),
  ('browning', 'X-Bolt Hunter', '.300 Win Mag', 'BROWNING-XBOLTHUNTER-300WINMAG', 3),
  ('merkel', 'Helix Alpinist', '.30-06 Sprg', 'MERKEL-HELIXALPINIST-3006SPRG', 1),
  ('merkel', 'Helix Alpinist', '9,3x62', 'MERKEL-HELIXALPINIST-93X62', 2),
  ('browning', 'BAR MK3', '.30-06 Sprg', 'BROWNING-BARMK3-3006SPRG', 1),
  ('browning', 'BAR MK3', '.300 Win Mag', 'BROWNING-BARMK3-300WINMAG', 2),
  ('benelli', 'Argo E Comfort', '.30-06 Sprg', 'BENELLI-ARGOECOMFORT-3006SPRG', 1),
  ('benelli', 'Argo E Comfort', '.300 Win Mag', 'BENELLI-ARGOECOMFORT-300WINMAG', 2),
  ('cz', '457 Varmint', '.22 LR', 'CZ-457VARMINT-22LR', 1),
  ('anschutz', '1761 HB', '.22 LR', 'ANSCHUTZ-1761HB-22LR', 1),
  ('aya', 'No. 4/53', 'cal. 12/70', 'AYA-NO453-CAL1270', 1),
  ('aya', 'No. 4/53', 'cal. 20/70', 'AYA-NO453-CAL2070', 2),
  ('aya', 'No. 1 De Luxe', 'cal. 12/70', 'AYA-NO1DELUXE-CAL1270', 1),
  ('aya', 'No. 1 De Luxe', 'cal. 20/70', 'AYA-NO1DELUXE-CAL2070', 2),
  ('grulla-armas', '216 RB', 'cal. 12/70', 'GRULLAARMAS-216RB-CAL1270', 1),
  ('grulla-armas', '216 RB', 'cal. 20/70', 'GRULLAARMAS-216RB-CAL2070', 2),
  ('arrieta', '557', 'cal. 12/70', 'ARRIETA-557-CAL1270', 1),
  ('arrieta', '557', 'cal. 20/70', 'ARRIETA-557-CAL2070', 2),
  ('beretta', '686 Silver Pigeon I', 'cal. 12/76', 'BERETTA-686SILVERPIGEONI-CAL1276', 1),
  ('beretta', '686 Silver Pigeon I', 'cal. 20/76', 'BERETTA-686SILVERPIGEONI-CAL2076', 2),
  ('beretta', '690 Field III', 'cal. 12/76', 'BERETTA-690FIELDIII-CAL1276', 1),
  ('browning', 'B525 Game One', 'cal. 12/76', 'BROWNING-B525GAMEONE-CAL1276', 1),
  ('browning', 'B525 Game One', 'cal. 20/76', 'BROWNING-B525GAMEONE-CAL2076', 2),
  ('browning', 'B725 Sporter', 'cal. 12/76', 'BROWNING-B725SPORTER-CAL1276', 1),
  ('fabarm', 'Elos N2 Allsport', 'cal. 12/76', 'FABARM-ELOSN2ALLSPORT-CAL1276', 1),
  ('zoli', 'Z-Sport', 'cal. 12/76', 'ZOLI-ZSPORT-CAL1276', 1),
  ('benelli', 'Raffaello Crio', 'cal. 12/76', 'BENELLI-RAFFAELLOCRIO-CAL1276', 1),
  ('beretta', 'A400 Xtreme Plus', 'cal. 12/89', 'BERETTA-A400XTREMEPLUS-CAL1289', 1),
  ('winchester', 'SX4 Field', 'cal. 12/76', 'WINCHESTER-SX4FIELD-CAL1276', 1),
  ('winchester', 'SX4 Field', 'cal. 20/76', 'WINCHESTER-SX4FIELD-CAL2076', 2),
  ('pardini', 'SP', '.22 LR', 'PARDINI-SP-22LR', 1),
  ('pardini', 'K12 Absorber', '4,5 mm', 'PARDINI-K12ABSORBER-45MM', 1),
  ('walther', 'GSP Expert', '.22 LR', 'WALTHER-GSPEXPERT-22LR', 1),
  ('walther', 'LP500 Expert', '4,5 mm', 'WALTHER-LP500EXPERT-45MM', 1),
  ('morini', 'CM 162 EI', '4,5 mm', 'MORINI-CM162EI-45MM', 1),
  ('feinwerkbau', 'AW93', '.22 LR', 'FEINWERKBAU-AW93-22LR', 1),
  ('steyr', 'EVO 10 E', '4,5 mm', 'STEYR-EVO10E-45MM', 1),
  ('beretta', '92X Performance', '9 mm Pb', 'BERETTA-92XPERFORMANCE-9MMPB', 1),
  ('cz', 'Shadow 2', '9 mm Pb', 'CZ-SHADOW2-9MMPB', 1),
  ('glock', '17 Gen5', '9 mm Pb', 'GLOCK-17GEN5-9MMPB', 1),
  ('sig-sauer', 'P226 LDC II', '9 mm Pb', 'SIGSAUER-P226LDCII-9MMPB', 1),
  ('federal', 'Power-Shok .308 Win 150 gr', '.308 Win', 'FEDERAL-POWERSHOK308WIN150GR-308WIN', 1),
  ('hornady', 'Precision Hunter 6,5 Creedmoor 143 gr', '6,5 Creedmoor', 'HORNADY-PRECISIONHUNTER65CREEDMOOR143GR-65CREEDMOOR', 1),
  ('hornady', 'Superformance .30-06 Sprg 165 gr', '.30-06 Sprg', 'HORNADY-SUPERFORMANCE3006SPRG165GR-3006SPRG', 1),
  ('rws', 'Evolution Green .308 Win 139 gr', '.308 Win', 'RWS-EVOLUTIONGREEN308WIN139GR-308WIN', 1),
  ('norma', 'Oryx .30-06 Sprg 180 gr', '.30-06 Sprg', 'NORMA-ORYX3006SPRG180GR-3006SPRG', 1),
  ('sellier', '.308 Win 147 gr', '.308 Win', 'SELLIER-308WIN147GR-308WIN', 1),
  ('lapua', 'Scenar-L 6,5 Creedmoor 136 gr', '6,5 Creedmoor', 'LAPUA-SCENARL65CREEDMOOR136GR-65CREEDMOOR', 1),
  ('cci', 'Standard Velocity .22 LR 40 gr', '.22 LR', 'CCI-STANDARDVELOCITY22LR40GR-22LR', 1),
  ('eley', 'Tenex .22 LR 40 gr', '.22 LR', 'ELEY-TENEX22LR40GR-22LR', 1),
  ('rio', 'Game Load BlueSteel cal. 12/70', 'cal. 12/70', 'RIO-GAMELOADBLUESTEELCAL1270-CAL1270', 1),
  ('saga', 'Heavy 34 cal. 12/70', 'cal. 12/70', 'SAGA-HEAVY34CAL1270-CAL1270', 1),
  ('fiocchi', 'Golden Pheasant cal. 12/70', 'cal. 12/70', 'FIOCCHI-GOLDENPHEASANTCAL1270-CAL1270', 1),
  ('winchester', 'Super X cal. 12/76', 'cal. 12/76', 'WINCHESTER-SUPERXCAL1276-CAL1276', 1)
  ) as v(brand, ref, calibre, sku, position)
  join public.brand   b on b.slug = v.brand
  join public.product p on p.brand_id = b.id and p.ref = v.ref
  join public.calibre c on c.name = v.calibre
on conflict (product_id, calibre_id) do nothing;

insert into public.product_variant (product_id, calibre_id, sku, position)
select p.id, null, v.sku, v.position
  from (values
  ('swarovski', 'Z8i 2-16x50 P', 'SWAROVSKI-Z8I216X50P', 1),
  ('swarovski', 'Z6i 2,5-15x56', 'SWAROVSKI-Z6I2515X56', 1),
  ('zeiss', 'Conquest V4 3-12x56', 'ZEISS-CONQUESTV4312X56', 1),
  ('zeiss', 'Victory V8 2,8-20x56', 'ZEISS-VICTORYV82820X56', 1),
  ('leupold', 'VX-3HD 3,5-10x50', 'LEUPOLD-VX3HD3510X50', 1),
  ('vortex', 'Viper PST Gen II 5-25x50', 'VORTEX-VIPERPSTGENII525X50', 1),
  ('kahles', 'K18i 1-8x24', 'KAHLES-K18I18X24', 1),
  ('aimpoint', 'Micro H-2 2 MOA', 'AIMPOINT-MICROH22MOA', 1),
  ('aimpoint', 'Acro P-2 3,5 MOA', 'AIMPOINT-ACROP235MOA', 1),
  ('holosun', 'HS507C X2', 'HOLOSUN-HS507CX2', 1),
  ('swarovski', 'EL 10x42 WB', 'SWAROVSKI-EL10X42WB', 1),
  ('zeiss', 'Victory SF 10x42', 'ZEISS-VICTORYSF10X42', 1),
  ('leica', 'Geovid R 10x42', 'LEICA-GEOVIDR10X42', 1),
  ('vortex', 'Diamondback HD 10x42', 'VORTEX-DIAMONDBACKHD10X42', 1),
  ('peli', '1750 Protector', 'PELI-1750PROTECTOR', 1),
  ('peli', '1720 Protector', 'PELI-1720PROTECTOR', 1),
  ('negrini', '1657', 'NEGRINI-1657', 1),
  ('plano', 'All Weather 42"', 'PLANO-ALLWEATHER42', 1),
  ('beretta', 'Hunter Tech Rifle Case', 'BERETTA-HUNTERTECHRIFLECASE', 1),
  ('beretta', 'Uniform Pro EVO Field Bag', 'BERETTA-UNIFORMPROEVOFIELDBAG', 1),
  ('arregui', 'Braco 5', 'ARREGUI-BRACO5', 1),
  ('rottner', 'Gun 5 Cargo', 'ROTTNER-GUN5CARGO', 1),
  ('hoppe-s', 'No. 9 Deluxe Kit', 'HOPPES-NO9DELUXEKIT', 1),
  ('otis', 'Elite Cleaning System', 'OTIS-ELITECLEANINGSYSTEM', 1)
  ) as v(brand, ref, sku, position)
  join public.brand   b on b.slug = v.brand
  join public.product p on p.brand_id = b.id and p.ref = v.ref
on conflict (sku) do nothing;

insert into public.product_photo (product_id, path, is_primary, licence_note)
select p.id, v.path, true, 'sin aclarar: foto de fabricante o distribuidor'
  from (values
  ('bergara', 'B-14 Ridge', 'img/product/bergara-b-14-ridge.webp'),
  ('bergara', 'B-14 HMR', 'img/product/bergara-b-14-hmr.webp'),
  ('tikka', 'T3x Lite', 'img/product/tikka-t3x-lite.webp'),
  ('tikka', 'T3x Varmint', 'img/product/tikka-t3x-varmint.webp'),
  ('sako', '85 Bavarian', 'img/product/sako-85-bavarian.webp'),
  ('sako', 'S20 Hunter', 'img/product/sako-s20-hunter.webp'),
  ('blaser', 'R8 Professional', 'img/product/blaser-r8-professional.webp'),
  ('sauer', '100 Classic XT', 'img/product/sauer-100-classic-xt.webp'),
  ('mauser', 'M12 Pure', 'img/product/mauser-m12-pure.webp'),
  ('browning', 'X-Bolt Hunter', 'img/product/browning-x-bolt-hunter.webp'),
  ('merkel', 'Helix Alpinist', 'img/product/merkel-helix-alpinist.webp'),
  ('browning', 'BAR MK3', 'img/product/browning-bar-mk3.webp'),
  ('benelli', 'Argo E Comfort', 'img/product/benelli-argo-e-comfort.webp'),
  ('cz', '457 Varmint', 'img/product/cz-457-varmint.webp'),
  ('anschutz', '1761 HB', 'img/product/anschutz-1761-hb.webp'),
  ('aya', 'No. 4/53', 'img/product/aya-no-4-53.webp'),
  ('aya', 'No. 1 De Luxe', 'img/product/aya-no-1-de-luxe.webp'),
  ('grulla-armas', '216 RB', 'img/product/grulla-armas-216-rb.webp'),
  ('arrieta', '557', 'img/product/arrieta-557.webp'),
  ('beretta', '686 Silver Pigeon I', 'img/product/beretta-686-silver-pigeon-i.webp'),
  ('beretta', '690 Field III', 'img/product/beretta-690-field-iii.webp'),
  ('browning', 'B525 Game One', 'img/product/browning-b525-game-one.webp'),
  ('browning', 'B725 Sporter', 'img/product/browning-b725-sporter.webp'),
  ('fabarm', 'Elos N2 Allsport', 'img/product/fabarm-elos-n2-allsport.webp'),
  ('zoli', 'Z-Sport', 'img/product/zoli-z-sport.webp'),
  ('benelli', 'Raffaello Crio', 'img/product/benelli-raffaello-crio.webp'),
  ('beretta', 'A400 Xtreme Plus', 'img/product/beretta-a400-xtreme-plus.webp'),
  ('winchester', 'SX4 Field', 'img/product/winchester-sx4-field.webp'),
  ('pardini', 'SP', 'img/product/pardini-sp.webp'),
  ('pardini', 'K12 Absorber', 'img/product/pardini-k12-absorber.webp'),
  ('walther', 'GSP Expert', 'img/product/walther-gsp-expert.webp'),
  ('walther', 'LP500 Expert', 'img/product/walther-lp500-expert.webp'),
  ('morini', 'CM 162 EI', 'img/product/morini-cm-162-ei.webp'),
  ('feinwerkbau', 'AW93', 'img/product/feinwerkbau-aw93.webp'),
  ('steyr', 'EVO 10 E', 'img/product/steyr-evo-10-e.webp'),
  ('beretta', '92X Performance', 'img/product/beretta-92x-performance.webp'),
  ('cz', 'Shadow 2', 'img/product/cz-shadow-2.webp'),
  ('glock', '17 Gen5', 'img/product/glock-17-gen5.webp'),
  ('sig-sauer', 'P226 LDC II', 'img/product/sig-sauer-p226-ldc-ii.webp'),
  ('swarovski', 'Z8i 2-16x50 P', 'img/product/swarovski-z8i-2-16x50-p.webp'),
  ('swarovski', 'Z6i 2,5-15x56', 'img/product/swarovski-z6i-2-5-15x56.webp'),
  ('zeiss', 'Conquest V4 3-12x56', 'img/product/zeiss-conquest-v4-3-12x56.webp'),
  ('zeiss', 'Victory V8 2,8-20x56', 'img/product/zeiss-victory-v8-2-8-20x56.webp'),
  ('leupold', 'VX-3HD 3,5-10x50', 'img/product/leupold-vx-3hd-3-5-10x50.webp'),
  ('vortex', 'Viper PST Gen II 5-25x50', 'img/product/vortex-viper-pst-gen-ii-5-25x50.webp'),
  ('kahles', 'K18i 1-8x24', 'img/product/kahles-k18i-1-8x24.webp'),
  ('aimpoint', 'Micro H-2 2 MOA', 'img/product/aimpoint-micro-h-2-2-moa.webp'),
  ('aimpoint', 'Acro P-2 3,5 MOA', 'img/product/aimpoint-acro-p-2-3-5-moa.webp'),
  ('holosun', 'HS507C X2', 'img/product/holosun-hs507c-x2.webp'),
  ('swarovski', 'EL 10x42 WB', 'img/product/swarovski-el-10x42-wb.webp'),
  ('zeiss', 'Victory SF 10x42', 'img/product/zeiss-victory-sf-10x42.webp'),
  ('leica', 'Geovid R 10x42', 'img/product/leica-geovid-r-10x42.webp'),
  ('vortex', 'Diamondback HD 10x42', 'img/product/vortex-diamondback-hd-10x42.webp'),
  ('federal', 'Power-Shok .308 Win 150 gr', 'img/product/federal-power-shok-308-win-150-gr.webp'),
  ('hornady', 'Precision Hunter 6,5 Creedmoor 143 gr', 'img/product/hornady-precision-hunter-6-5-creedmoor-143-gr.webp'),
  ('hornady', 'Superformance .30-06 Sprg 165 gr', 'img/product/hornady-superformance-30-06-sprg-165-gr.webp'),
  ('rws', 'Evolution Green .308 Win 139 gr', 'img/product/rws-evolution-green-308-win-139-gr.webp'),
  ('norma', 'Oryx .30-06 Sprg 180 gr', 'img/product/norma-oryx-30-06-sprg-180-gr.webp'),
  ('sellier', '.308 Win 147 gr', 'img/product/sellier-bellot-308-win-147-gr.webp'),
  ('lapua', 'Scenar-L 6,5 Creedmoor 136 gr', 'img/product/lapua-scenar-l-6-5-creedmoor-136-gr.webp'),
  ('cci', 'Standard Velocity .22 LR 40 gr', 'img/product/cci-standard-velocity-22-lr-40-gr.webp'),
  ('eley', 'Tenex .22 LR 40 gr', 'img/product/eley-tenex-22-lr-40-gr.webp'),
  ('rio', 'Game Load BlueSteel cal. 12/70', 'img/product/rio-game-load-bluesteel-cal-12-70.webp'),
  ('saga', 'Heavy 34 cal. 12/70', 'img/product/saga-heavy-34-cal-12-70.webp'),
  ('fiocchi', 'Golden Pheasant cal. 12/70', 'img/product/fiocchi-golden-pheasant-cal-12-70.webp'),
  ('winchester', 'Super X cal. 12/76', 'img/product/winchester-super-x-cal-12-76.webp'),
  ('peli', '1750 Protector', 'img/product/peli-1750-protector.webp'),
  ('peli', '1720 Protector', 'img/product/peli-1720-protector.webp'),
  ('negrini', '1657', 'img/product/negrini-1657.webp'),
  ('plano', 'All Weather 42"', 'img/product/plano-all-weather-42.webp'),
  ('beretta', 'Hunter Tech Rifle Case', 'img/product/beretta-hunter-tech-rifle-case.webp'),
  ('beretta', 'Uniform Pro EVO Field Bag', 'img/product/beretta-uniform-pro-evo-field-bag.webp'),
  ('arregui', 'Braco 5', 'img/product/arregui-braco-5.webp'),
  ('rottner', 'Gun 5 Cargo', 'img/product/rottner-gun-5-cargo.webp'),
  ('hoppe-s', 'No. 9 Deluxe Kit', 'img/product/hoppe-s-no-9-deluxe-kit.webp'),
  ('otis', 'Elite Cleaning System', 'img/product/otis-elite-cleaning-system.webp')
  ) as v(brand, ref, path)
  join public.brand   b on b.slug = v.brand
  join public.product p on p.brand_id = b.id and p.ref = v.ref
on conflict (product_id, path) do nothing;
